#!/bin/sh

# Copyright (C) 2007-2016 Segher Boessenkool <segher@kernel.crashing.org>
# Released under the terms of the GNU GPL, version 2

BDIR=$( (cd `dirname $0` ; pwd))
. $BDIR/config

$ECHO "================== Primary platforms ========================="
./build "$@" arm multi_v5_defconfig
./build "$@" armhf # multi_v7_defconfig, which is default
./build "$@" arm64
./build "$@" i386
./build "$@" riscv32 riscv32_defconfig
./build "$@" riscv64
./build "$@" x86_64
$ECHO "================== Secondary platforms ======================="
./build "$@" mips
./build "$@" mips64 ip32_defconfig
./build "$@" powerpc ppc6xx_defconfig
./build "$@" powerpc64
./build "$@" powerpc64le ppc64le_defconfig
./build "$@" s390
./build "$@" sparc
./build "$@" sparc64
$ECHO "================== Tertiary platforms ========================"
./build "$@" alpha
./build "$@" arc nsim_700_defconfig
./build "$@" arcv2 axs103_defconfig
./build "$@" csky
# Needs 12.1 or later. Fails to build in 12.1.
./build "$@" loongarch64
./build "$@" m68k
./build "$@" nios2
./build "$@" openrisc
./build "$@" parisc
./build "$@" parisc64 a500_defconfig
./build "$@" sh se7750_defconfig
./build "$@" sheb se7750_defconfig
./build "$@" shnommu se7619_defconfig
./build "$@" xtensa
$ECHO "================== Obsolete platforms ======================="
# ./build "$@" c6x			# No longer tested
# ./build "$@" ia64			# No longer tested
./build "$@" nds32			# removed in Linux v6.1+
./build "$@" h8300 edosk2674_defconfig	# removed in Linux v6.1+
$ECHO "================== Imaginary platforms ======================="
./build "$@" microblaze
./build "$@" microblazeel

# Not in GCC:
# hexagon
